name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am Seoul
    - cron: '00 15 * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: kich555/kich555@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LOCALE: "ko" 
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          SYMBOL_VERSION: 3
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
